'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class carga_archivo
    Public Property id_carga_archivo As Integer
    Public Property cargado As Nullable(Of Integer)
    Public Property fecha As String
    Public Property usuario As String
    Public Property hora As String
    Public Property descripcion As String
    Public Property tipo As Nullable(Of Integer)
    Public Property fecha_crea As String

End Class
