'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cuenta
    Public Property Numero As Integer
    Public Property Nombre As String
    Public Property fk_tipo_cuenta As Nullable(Of Integer)

    Public Overridable Property Archivo As ICollection(Of Archivo) = New HashSet(Of Archivo)
    Public Overridable Property tipo_cuenta As tipo_cuenta

End Class
