'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class permiso_asignado
    Public Property id_asignado As Integer
    Public Property fk_rol As Integer
    Public Property fk_permiso As Integer

    Public Overridable Property permiso As permiso
    Public Overridable Property Rol As Rol

End Class
