'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipo_transaccion
    Public Property id_tipo_transaccion As Integer
    Public Property descripcion As String

    Public Overridable Property Archivo As ICollection(Of Archivo) = New HashSet(Of Archivo)

End Class
