'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipo_cuenta
    Public Property id_tipo_cuenta As Integer
    Public Property nombre As String

    Public Overridable Property Cuenta As ICollection(Of Cuenta) = New HashSet(Of Cuenta)

End Class
