'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property id_usuario As Integer
    Public Property nombre As String
    Public Property contraseña As String
    Public Property creacion As Date
    Public Property estado As Integer
    Public Property rol As Integer
    Public Property asignado As Nullable(Of Boolean)

    Public Overridable Property persona As ICollection(Of persona) = New HashSet(Of persona)
    Public Overridable Property Rol1 As Rol

End Class
